config/routes.rb
Rails.application.routes.draw do
  resources :scores
      devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }

  get "welcome/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "welcome#index"
end

app/models/score.rb
class Score < ApplicationRecord
belongs_to :user
belongs_to :composer
after_update :hey
after_create :hey
def hey




@score="
<lilypond fragment staffsize=26>
  \\key #{key_signature.sub(" "," \\")}
  \\numericTimeSignature
  \\time #{time_signature}
  #{myscore}
</lilypond>




"

p @score

wow="./public/uploads/"
hi=self.title.parameterize
p wow+hi
File.write(wow+"hey"+hi+".html", @score)
@hey=`(cd #{wow} && lilypond-book hey#{hi}.html -f html --output #{hi})`

end

end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :set_score, only: %i[ show edit update destroy ]

  # GET /scores or /scores.json
  def index
    @scores = Score.all
  end

  # GET /scores/1 or /scores/1.json
  def show
  end

  # GET /scores/new
  def new
    @score = Score.new(user_id: current_user.try(:id))
  end

  # GET /scores/1/edit
  def edit
  end

  # POST /scores or /scores.json
  def create
    @score = Score.new(score_params)

    respond_to do |format|
      if @score.save
        format.html { redirect_to @score, notice: "Score was successfully created." }
        format.json { render :show, status: :created, location: @score }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scores/1 or /scores/1.json
  def update
    respond_to do |format|
      if @score.update(score_params)
        format.html { redirect_to @score, notice: "Score was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @score }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scores/1 or /scores/1.json
  def destroy
    @score.destroy!

    respond_to do |format|
      format.html { redirect_to scores_path, notice: "Score was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_score
      @score = Score.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def score_params
      params.expect(score: [ :user_id, :title, :composer_id, :title, :description, :myscore, :time_signature, :key_signature ])
    end
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/scores/_form.html.erb
<%= form_with(model: score) do |form| %>
  <% if score.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(score.errors.count, "error") %> prohibited this score from being saved:</h2>

      <ul>
        <% score.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :composer_id, style: "display: block" %>
    <%= form.select :composer_id, Composer.all.collect{|h|["#{h.name}", h.id]}, {selected: params[:composer_id]} %>
  </div>

    <%= form.hidden_field :user_id %>
  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :myscore, style: "display: block" %>
    <%= form.text_area :myscore, style: "width:100%;height:500px;" %>
  </div>
  <div>
    <%= form.label :time_signature, style: "display: block" %>
    <%= form.text_field :time_signature %>
  </div>
  <div>
    <%= form.label :key_signature, style: "display: block" %>
    <%= form.text_field :key_signature %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/scores/_score.html.erb
<div id="<%= dom_id score %>">
  <p>
    <strong>score:</strong>
    <%= score.title %>
    <%= score.composer.name %>
  </p>
  <p>
    <strong>Title:</strong>
    <%= score.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= score.description %>
  </p>

  <p>
<iframe style="width:90%;height:1000px;" src="/uploads/<%=score.title.parameterize%>/hey<%=score.title.parameterize%>.html">
</iframe>

  </p>

</div>

app/views/scores/edit.html.erb
<% content_for :title, "Editing score" %>

<h1>Editing score</h1>

<%= render "form", score: @score %>

<br>

<div>
  <%= link_to "Show this score", @score %> |
  <%= link_to "Back to scores", scores_path %>
</div>

app/views/scores/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Scores" %>

<h1>Scores</h1>

<div id="scores">
  <% @scores.each do |score| %>
    <%= render score %>
    <p>
      <%= link_to "Show this score", score %>
    </p>
  <% end %>
</div>

<%current_user.composers.each do |h|%>
<%= link_to "New score by #{h.name}", new_score_path(composer_id: h.id) %>
<%end%>

app/views/scores/new.html.erb
<% content_for :title, "New score" %>

<h1>New score</h1>

<%= render "form", score: @score %>

<br>

<div>
  <%= link_to "Back to scores", scores_path %>
</div>

app/views/scores/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @score %>

<div>
  <%= link_to "Edit this score", edit_score_path(@score) %> |
  <%= link_to "Back to scores", scores_path %>

  <%= button_to "Destroy this score", @score, method: :delete %>
</div>